Bram
ramonluteijn/Sagrada pull request #71
Opened 2024-04-20 08:50 UTC by Keranus

Pull request op verzoek van Jurian, alsjeblieft broeder

2024-04-20 12:44 UTC, ramonluteijn reviewed
buiten de comments ziet het er denk ik wel prima uit

2024-04-20 12:44 UTC, ramonluteijn commented on src/View/PlayersView.java
deze zou je misschien nog wat kunnen optimaliseren door het maken van een methode waar je een variabelen aan meegeeft. de rest van de waardes zijn namelijk elke keer hetzelfde

2024-04-20 12:44 UTC, ramonluteijn commented on src/View/SearchBarView.java
> +		searchBar = new TextField("Vul een gebruikersnaam in");
je kan de setpropttext misschien beter doen, dat is namelijk echt een placholder en niet echt text die je weg moet halen zoals het nu wel is

2024-04-22 12:35 UTC, Tommy030 requested changes
Geef betere PR namen aub

2024-04-22 12:43 UTC, Tommy030 requested changes
Geef betere PR naam ook aub

2024-04-22 12:43 UTC, Tommy030 commented on src/View/FavorTokensView.java
> +		layoutX = new HBox();
Is een HBOX wel nodig aangezien de klasse zelf een hbox is?

2024-04-24 08:56 UTC, merged